################################################
#  wxWidgets and OpenLDAP developpement packages
#  must be installed on the system.
#  wxWidgets must be compiled with Unicode support.
#  The wxWidgets contrib developpement package must
#  also be installed (XMLResource system)
################################################


TOOLNAME=ldapexplorertool2

################################################
#    Include directories to add with when using wxWidgets
#    The best way to do this is to use the wx-config tool
#    provided by wxWidgets
################################################

WX_INC=$(shell wx-config --cflags)


################################################
#    Libraries to link with when using wxWidgets
#    The best way to do this is to use the wx-config tool
#    provided by wxWidgets
################################################

# Debian Etch / Windows
WX_LIB=$(shell wx-config --libs) 
# Debian Sage (3.1) - wxGTK 2.4
#WX_LIB=$(shell wx-config --libs) -lwx_gtk_xrc-2.4


################################################
#    Include directories to add when using OpenLDAP
#    For most systems leave empty.
################################################


# Specific to my install of OpenLDAP / MinGw
LDAP_INC=-I/usr/local/include
#LDAP_INC=-I/usr/include

################################################
#    Libraries to link with when using OpenLDAP
################################################

LDAP_LIB=-lldap -llber

################################################
#    Libraries to link with when using OpenLDAP
################################################


XRC_DIR=$(DESTDIR)/usr/share/$(TOOLNAME)
#XRC_DIR=./xrc/
#TOOL_DIR=$(HOME)/$(TOOLNAME)
TOOL_DIR=$(DESTDIR)/usr/bin
